---
title: '**Results Template**'
subtitle: Clustering
output:
  html_document:
    theme: cerulean
    highlight: pygments
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: no
    df_print: kable
    code_folding: hide
    code_download: yes
  word_document:
    reference_docx: utils/Template_Word.docx
    highlight: pygments
    toc: no
    toc_depth: 3
    df_print: kable
    number_sections: yes
  rmarkdown::html_vignette:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '2'
    latex_engine: xelatex
editor_options:
  chunk_output_type: console
bibliography: utils/bibliography.bib
csl: utils/apa.csl
---


<!-- 
!!!! IMPORTANT: run `source("utils/render.R")` to publish instead of clicking on 'Knit'
-->

```{r setup, warning=FALSE, message=TRUE, include=FALSE}
# Set up the environment (or use local alternative `source("utils/config.R")`)
source("https://raw.githubusercontent.com/RealityBending/TemplateResults/main/utils/config.R")  

fast <- FALSE  # Make this false to skip the chunks
```

# Introduction



```{r warning=FALSE, message=TRUE, results='asis'}
library(easystats)

summary(report::report(sessionInfo()))
```


## Data

```{r warning=FALSE, message=TRUE, results='asis'}
df <- read_csv("data/class_wide_1.csv")
```


```{r child=if (fast == FALSE) '1_clustering.Rmd'}
```

# Full Code

The full script of executive code contained in this document is reproduced here.

```{r full_code, ref.label=knitr::all_labels(), eval=FALSE}
```

# Package References

```{r warning=FALSE, message=FALSE, results='asis'}
report::cite_packages(sessionInfo())
```


# References
